def gatError():
    try:
    pass
    exception:
    pass